[book]
authors = ["Marco Ma"]
language = "en"
multilingual = false
src = "src"
title = "momenTUM Research Platform"

[output.html]
additional-css = ["css/custom.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]


[preprocessor.mermaid]
command = "mdbook-mermaid"
